### PR TITLE
Add catches

### PR DESCRIPTION
**Pull request by damianooldoni**
@LienReyserhove, @peterdesmet, I would like to have your review from at least one of you for this PR which aims to add VMM rattenapp catches I got yesterday from Dan (VMM). By publishing them, it will be easier for @LienReyserhove to write the metadata as big chunks of metadata of [MICA - Muskrat occs](https://www.gbif.org/dataset/3634aee3-41d5-4aa2-8cb5-875859f62a3a) dataset can be reused.

Catches have a slight different structure and so I preferred to first make some join operations in R.

I reused `samplingProtocol`  value `rat trap` for the catches as this is the value in use in [MICA - Muskrat occs](https://www.gbif.org/dataset/3634aee3-41d5-4aa2-8cb5-875859f62a3a).

### CODE REVIEW

**Comment by LienReyserhove** [comment]
I had a glance, looks good! I have a two remarks:

- The field `language` is missing, should be set `en` (see https://github.com/riparias/vmm-rattenapp-occurrences/pull/8/commits/5e99c78a5b06779ac8856dced0ef9d06be0fe04f)
- `establishmentMeans` =  introduced` for 1 record only (`Sporen Waarnemingen Naam` = `Koe gered uit dyle`). A cow is not introduced but native. Many other species could receive the status of `introduced`, such as `Ondatra zibethicus`, ` Impatiens glandulifera`, `Fallopia japonica`, etc. Not sure why this particular record is `introduced`

**Comment by damianooldoni** [comment]
@peterdesmet: I remember you set it `introduced` to the cow record 😄 the idea behind was to flag it as a bred animal (for plants we would say that it is _cultivated_). But as @LienReyserhove noticed I think we misused the field.

My idea: remove field `establishmentMeans` field for all records and remove the cow record as well as it is a captive organism. For instance, iNaturalist doesn't push such observations to GBIF.
@peterdesmet, @LienReyserhove: do you agree?

**Comment by peterdesmet** [comment]
Sounds good to me.

**Comment by LienReyserhove** [comment]
ok for me!

**Comment by damianooldoni** [comment]
Thanks. I will apply this change.

**Pull request merged**
